In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('pulsar_stars.csv')
data

,mip,sip,ekip,skip,mdmsnr,sdmsnr,edmsnr,skdmsnr,target_class
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225,0
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580,0
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909,0
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661,0
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306,0
...,...,...,...,...,...,...,...,...,...
11107,109.031250,44.131716,0.346662,0.246380,3.198997,20.086116,7.537774,62.864134,0
11108,124.601562,43.716476,0.260194,0.438259,1.863712,13.494666,10.014444,132.247682,0
11109,99.046875,53.078783,0.711107,0.293116,44.435619,74.737903,1.337398,0.146472,0
11110,132.625000,49.281716,-0.003375,-0.303483,2.880435,15.266800,8.090141,89.660099,0
11111,109.679688,54.310728,0.309497,-0.212051,2.795151,17.103091,8.308326,82.376371,0

In [3]:
type(data)

pandas.core.frame.DataFrame

In [4]:
new_data = dict()

In [5]:
new_data['mip5_100'] = (data['mip']<=100).astype(int)
new_data['mip100_145'] = ((data['mip']>100) & (data['mip']<=145)).astype(int)
new_data['mip145_193'] = (data['mip']>145).astype(int)

new_data['sip24_43'] = (data['sip']<=43).astype(int)
new_data['sip43_58'] = ((data['sip']>43) & (data['sip']<=58)).astype(int)
new_data['sip58_98'] = ((data['sip']>58) & (data['sip']<99)).astype(int)



new_data['ekipn'] = (data['ekip']<0).astype(int)
new_data['ekipp'] = (data['ekip']>=0).astype(int)

new_data['skipn'] = (data['skip']<0).astype(int)
new_data['skipp'] = (data['skip']>=0).astype(int)

new_data['mDMSNR0_11'] = (data['mdmsnr']<11).astype(int)
new_data['mDMSNR11_223'] = (data['mdmsnr']>=11).astype(int)


new_data['sDMSNR0_38'] = (data['sdmsnr']<38).astype(int)
new_data['sDMSNR38_111'] = (data['sdmsnr']>=38).astype(int)


new_data['ekDMSNR_6'] = (data['edmsnr']<=6).astype(int)
new_data['ekDMSNR6_14'] = ((data['edmsnr']>6) & (data['edmsnr']<=14)).astype(int)
new_data['ekDMSNR14_35'] = ((data['edmsnr']>14) & (data['edmsnr']<35)).astype(int)

new_data['skDMSNR_415'] = (data['skdmsnr']<415).astype(int)
new_data['skDMSNR415_1190'] = (data['skdmsnr']>=415).astype(int)



new_data['target'] = data['target_class']

In [6]:
df = pd.DataFrame(new_data)

In [7]:
df

,mip5_100,mip100_145,mip145_193,sip24_43,sip43_58,sip58_98,ekipn,ekipp,skipn,skipp,mDMSNR0_11,mDMSNR11_223,sDMSNR0_38,sDMSNR38_111,ekDMSNR_6,ekDMSNR6_14,ekDMSNR14_35,skDMSNR_415,skDMSNR415_1190,target
0,0,1,0,0,1,0,1,0,1,0,1,0,1,0,0,1,0,1,0,0
1,0,1,0,0,0,1,0,1,1,0,1,0,1,0,0,1,0,1,0,0
2,0,1,0,1,0,0,0,1,0,1,1,0,1,0,0,1,0,1,0,0
3,0,1,0,0,1,0,1,0,1,0,1,0,1,0,0,1,0,1,0,0
4,1,0,0,1,0,0,0,1,0,1,1,0,1,0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11107,0,1,0,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,0,0
11108,0,1,0,0,1,0,0,1,0,1,1,0,1,0,0,1,0,1,0,0
11109,1,0,0,0,1,0,0,1,0,1,0,1,0,1,1,0,0,1,0,0
11110,0,1,0,0,1,0,1,0,1,0,1,0,1,0,0,1,0,1,0,0
11111,0,1,0,0,1,0,0,1,1,0,1,0,1,0,0,1,0,1,0,0

In [8]:
from sklearn.model_selection import train_test_split
from sklearn import preprocessing, metrics

In [9]:
def make_intent(example):
    attrib = []
    for j in range(len(example)):
        attrib.append(j)
        
    return set([str(i)+':'+str(k) for i,k in zip(attrib,example)])

In [10]:
def intersect(example, context):
    intent = make_intent(example)
    intersection_res = []
    count = 0
    for i in context:
        intersection_x = intent&i
        if intersection_x:
            count = count + 1
            intersection_res.append(intersection_x)
    return [intersection_res, count]

In [11]:
def aggregate1(plus_massiv,  plus_count, minus_massiv, minus_count):
    psum = sum([len(p) for p in plus_massiv])
    size_plus = len(plus_massiv)
    msum = sum([len(p) for p in minus_massiv])
    size_minus = len(minus_massiv)
    k = plus_count/psum
    z = minus_count/msum
    return z>=k

In [12]:
def classifier1(X_train, X_test, y_train, y_test):
    X_tr = X_train.values.tolist()
    X_ts = X_test.values.tolist()
    y_tr = y_train.values.tolist()
    y_ts = y_test.values.tolist()

    plus_intent = [make_intent(O) for i, O in enumerate(X_tr) if y_tr[i]] 
    
    minus_intent = [make_intent(O) for i, O in enumerate(X_tr) if not y_tr[i]]
    
    results = {'tp': 0, 'fp': 0, 'tn': 0, 'fn': 0, 'contr': 0}
    
    for j, i in enumerate(X_ts):
        label = {'plus': False, 'minus': False}
        
        plus = intersect(i, plus_intent)
        minus = intersect(i, minus_intent)
        plus_massiv = plus[0]
        plus_count = plus[1]
        minus_massiv = minus[0]
        minus_count = minus[1]
        if aggregate1(plus_massiv,  plus_count, minus_massiv, minus_count):
            label['plus'] = True
        else:
            label['minus'] = True
        if label['plus'] and not label['minus']:
            if y_ts[j]:
                results['tn']+=1
            else: 
                results['fn']+=1
        elif label['minus'] and not label['plus']:
            if y_ts[j]:
                results['fp']+=1
            else: 
                results['tp']+=1
        else:
            results['contr']+=1
    return results

In [13]:
X = df[[d for d in df.head() if d != 'target']]
Y = df['target']


X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state = 1)
classif1 = classifier1(X_train, X_test, y_train, y_test)

In [14]:
classif1

{'tp': 2556, 'fp': 42, 'tn': 347, 'fn': 389, 'contr': 0}

In [15]:
accur = (classif1['tp'] + classif1['tn']) / (classif1['tp'] + classif1['tn'] + classif1['fp'] + classif1['fn'])
precision = classif1['tp'] / (classif1['tp'] + classif1['fp'])

recall = classif1['tp'] / (classif1['tp'] + classif1['fn'])
print("Aggregation function:   ")
print(" ")
print("accuracy:  ", accur*100)
print("precission:  ", precision*100)
print("recall:   ", recall*100)

Aggregation function:

accuracy:   87.07258548290342
precission:   98.38337182448036
recall:    86.7911714770798